name: Targets

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  llgo:
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - ubuntu-latest
        llvm: [21]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        uses: ./.github/actions/setup-deps
        with:
          llvm-version: ${{matrix.llvm}}

      - name: Set up Go for build
        uses: ./.github/actions/setup-go

      - name: Install
        run: |
          go install ./...
          echo "LLGO_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Build targets (empty)
        run: |
          cd _demo/embed/targetsbuild
          bash build.sh empty

      - name: Build targets (defer)
        run: |
          cd _demo/embed/targetsbuild
          bash build.sh defer
